# Generated by Django 3.1.1 on 2020-11-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20201122_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
