# Generated by Django 3.1.4 on 2020-12-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_file_analysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_Analysis',
        ),
    ]
