# Generated by Django 3.1.4 on 2020-12-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_file_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_analysis',
            name='reading_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file_analysis',
            name='reading_Time',
            field=models.IntegerField(default=0),
        ),
    ]
