# Generated by Django 3.1.4 on 2020-12-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20201220_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_Analysis',
        ),
    ]
